<?php
/**
 * @copyright 2018 Google Inc.
 * @license https://opensource.org/licenses/MIT MIT
 *
 * @link https://github.com/sass/dart-sass
 * @see lib/src/ast/node.dart@aa18e65f5
 */
namespace Sass\Ast;

/**
 * An [AstNode] that just exposes a single span generated by a callback.
 *
 * @author Anthon Pang <apang@softwaredevelopment.ca>
 */
class FakeAstNode extends AstNode
{
    /**
     * The callback to use to generate [span].
     *
     * @var callable
     */
    protected $callback;

    /**
     * Constructor
     *
     * @param callable $callback
     */
    public function __construct(callable $callback)
    {
        $this->callback = $callback;
    }

    /**
     * @return FileSpan
     */
    public function getSpan()
    {
        return call_user_func($this->callback);
    }
}
